import 'models.dart';

const genres = [
  'Adventure',
  'Animation',
  'Comedy',
  'Drama',
  'Mystery',
  'Sci-Fi',
];
const movies = [
  Movie(
    id: 'arrival',
    title: 'Arrival',
    year: 2016,
    minutes: 116,
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    symbol: '◎',
    colorValue: 0xff304954,
    description: 'A linguist searches for meaning when mysterious visitors arrive on Earth.',
  ),
  Movie(
    id: 'spiderverse',
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    minutes: 117,
    genres: ['Animation', 'Adventure', 'Comedy'],
    symbol: '✳',
    colorValue: 0xff733d70,
    description: 'Miles Morales discovers that being a hero can take more than one form.',
  ),
  Movie(
    id: 'knives',
    title: 'Knives Out',
    year: 2019,
    minutes: 130,
    genres: ['Mystery', 'Comedy', 'Drama'],
    symbol: '♜',
    colorValue: 0xff5d5030,
    description: 'An eccentric detective untangles a wealthy family’s complicated secrets.',
  ),
  Movie(
    id: 'paddington',
    title: 'Paddington 2',
    year: 2017,
    minutes: 103,
    genres: ['Comedy', 'Adventure'],
    symbol: '▧',
    colorValue: 0xffa54d36,
    description:
        'A kindhearted bear and a missing book lead to a grand adventure.',
  ),
  Movie(
    id: 'interstellar',
    title: 'Interstellar',
    year: 2014,
    minutes: 169,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    symbol: '◉',
    colorValue: 0xff32425e,
    description: 'Explorers travel beyond our galaxy in search of a future for humanity.',
  ),
  Movie(
    id: 'grand',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    minutes: 99,
    genres: ['Comedy', 'Adventure'],
    symbol: '♙',
    colorValue: 0xff94586f,
    description: 'A hotel concierge and his protégé are swept into a wonderfully odd caper.',
  ),
  Movie(
    id: 'coco',
    title: 'Coco',
    year: 2017,
    minutes: 105,
    genres: ['Animation', 'Adventure'],
    symbol: '❋',
    colorValue: 0xff8a472a,
    description:
        'An aspiring musician journeys through a world of family and memory.',
  ),
  Movie(
    id: 'martian',
    title: 'The Martian',
    year: 2015,
    minutes: 144,
    genres: ['Sci-Fi', 'Adventure'],
    symbol: '◌',
    colorValue: 0xff94542e,
    description:
        'A stranded astronaut turns science and optimism into a survival plan.',
  ),
  Movie(
    id: 'truman',
    title: 'The Truman Show',
    year: 1998,
    minutes: 103,
    genres: ['Drama', 'Comedy', 'Sci-Fi'],
    symbol: '◈',
    colorValue: 0xff3e746b,
    description:
        'An ordinary man questions the extraordinary world built around him.',
  ),
  Movie(
    id: 'zootopia',
    title: 'Zootopia',
    year: 2016,
    minutes: 108,
    genres: ['Animation', 'Comedy', 'Mystery'],
    symbol: '✧',
    colorValue: 0xff596c3c,
    description: 'An unlikely detective duo follows a mystery through a city of animals.',
  ),
  Movie(
    id: 'inception',
    title: 'Inception',
    year: 2010,
    minutes: 148,
    genres: ['Sci-Fi', 'Mystery', 'Adventure'],
    symbol: '◇',
    colorValue: 0xff425765,
    description:
        'A team enters the architecture of dreams for one last impossible job.',
  ),
  Movie(
    id: 'soul',
    title: 'Soul',
    year: 2020,
    minutes: 100,
    genres: ['Animation', 'Comedy', 'Drama'],
    symbol: '♫',
    colorValue: 0xff524e86,
    description:
        'A jazz musician finds meaning in the small moments of everyday life.',
  ),
];
